//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Bubble')
export class BubbleEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  position: string;

  @Column('text', { nullable: true })
  color: string;

  @Column('integer', { nullable: true })
  size: number;
}
