//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Player')
export class PlayerEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('bool', { nullable: true })
  shooting: boolean;
}
