//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Score')
export class ScoreEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  currentScore: number;

  @Column('integer', { nullable: true })
  highScore: number;

  @Column('integer', { nullable: true })
  level: number;
}
