//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Player: [
      { shooting: false, id: 71 },
      { shooting: false, id: 95 },
      { shooting: false, id: 57 },
      { shooting: true, id: 81 },
      { shooting: false, id: 71 },
    ],
    Bubble: [
      { position: 'position 1', color: 'color 1', size: 1, id: 22 },
      { position: 'position 2', color: 'color 2', size: 2, id: 38 },
      { position: 'position 3', color: 'color 3', size: 3, id: 19 },
      { position: 'position 4', color: 'color 4', size: 4, id: 97 },
      { position: 'position 5', color: 'color 5', size: 5, id: 5 },
    ],
    Score: [
      { currentScore: 1, highScore: 1, level: 1, id: 51 },
      { currentScore: 2, highScore: 2, level: 2, id: 95 },
      { currentScore: 3, highScore: 3, level: 3, id: 67 },
      { currentScore: 4, highScore: 4, level: 4, id: 13 },
      { currentScore: 5, highScore: 5, level: 5, id: 55 },
    ],
  },
};
export default data;
