//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Player: { name: 'Player', fields: { shooting: 'Shooting', id: 'id' } },
    Bubble: {
      name: 'Bubble',
      fields: { position: 'Position', color: 'Color', size: 'Size', id: 'id' },
    },
    Score: {
      name: 'Score',
      fields: {
        currentScore: 'Current Score',
        highScore: 'High Score',
        level: 'Level',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Player: {
      name: 'Player (fr)',
      fields: { shooting: 'Shooting (fr)', id: 'id' },
    },
    Bubble: {
      name: 'Bubble (fr)',
      fields: {
        position: 'Position (fr)',
        color: 'Color (fr)',
        size: 'Size (fr)',
        id: 'id',
      },
    },
    Score: {
      name: 'Score (fr)',
      fields: {
        currentScore: 'Current Score (fr)',
        highScore: 'High Score (fr)',
        level: 'Level (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
